# Generated by Django 5.2.10 on 2026-01-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="responded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
