# Generated by Django 5.2.10 on 2026-01-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                ("response", models.TextField(blank=True, null=True)),
                ("responded", models.BooleanField(default=False)),
            ],
        ),
    ]
